import{a as h,S as L,i as l}from"./assets/vendor-DcHCnVjq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();var b=15;async function q(t,r){return await h.get("https://pixabay.com/api/",{params:{key:"56037316-398dfc4475139038527660650",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:b}}).then(e=>e.data)}const n={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")},S=new L(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,captionPosition:"bottom"}),u="is-visible";function v(t){const r=t.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:i,comments:f,downloads:y})=>`
    <li class='gallery-item'>
      <a class='gallery-link' href='${s}'>
        <img class='gallery-image' src='${a}' alt='${e}' />
      </a>
      <div class='image-info'>
        <p><span>Likes</span>${o}</p>
        <p><span>Views</span>${i}</p>
        <p><span>Comments</span>${f}</p>
        <p><span>Downloads</span>${y}</p>
      </div>
    </li>
    `).join("");n.gallery.insertAdjacentHTML("beforeend",r),S.refresh()}function w(){n.gallery.innerHTML=""}function B(){n.loader.classList.add(u)}function M(){n.loader.classList.remove(u)}function P(){n.loadMoreBtn.classList.add(u)}function x(){n.loadMoreBtn.classList.remove(u)}const g={searchForm:document.querySelector(".form"),loadMoreBtn:document.querySelector(".load-more-btn")};let d="",c=1,p=0;const E="Please, enter query for search!",$="Sorry, there are no images matching your search query. Please try again!",N="An error occurred. Please, try again later!",O="We're sorry, but you've reached the end of search results.";g.searchForm.addEventListener("submit",t=>{t.preventDefault();const r=t.currentTarget.elements["search-text"].value.trim();if(r===""){l.warning({title:"Warning",message:E,position:"topRight"});return}d=r,c=1,p=0,w(),m(t,d,c)});g.loadMoreBtn.addEventListener("click",()=>{c++,m(null,d,c)});function m(t,r,a){x(),B();let s=0;q(r,a).then(e=>{s=e.totalHits,p+=e.hits.length,e.hits.length===0?l.error({title:"Error",message:$,position:"topRight"}):(v(e.hits),R())}).catch(e=>{console.log(e),l.error({title:"Error",message:N,position:"topRight"})}).finally(()=>{M(),s>p?P():s!==0&&l.info({title:"Info",message:O,position:"topRight"}),t!==null&&t.target.reset()})}function R(){const t=document.querySelector(".gallery-item");if(t){console.log(t);const r=t.getBoundingClientRect().height;console.log(r),window.scrollBy({top:2*r,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
